export type Slide = {
  id: number
  section: string
  title: string
  bullets: string[]
  diagram?: string
  teacherNotes: {
    time: string
    explain: string
    mainIdea: string
    example: string
    question: string
    transition: string
    note?: string
  }
}

export const slides: Slide[] = [
  {
    id: 1,
    section: 'Introducción',
    title: 'Desarrollo con Agentes de IA',
    bullets: ['Del IDE al ADE', 'Workshop práctico · 2 horas', 'Pablo Botta'],
    teacherNotes: {
      time: '1 min',
      explain: 'Título, duración, que es práctico y que hay un desafío asincrónico al final.',
      mainIdea: 'No venimos a construir IA. Venimos a usarla como parte del oficio de desarrollar.',
      example: 'Mostrar el sitio: contenidos, actividad, desafío. “Todo queda acá.”',
      question: '¿Quién ya le pidió código a una IA esta semana?',
      transition: 'Anoten esa herramienta mentalmente. En 15 minutos la vamos a clasificar.',
    },
  },
  {
    id: 2,
    section: 'Introducción',
    title: '¿Por qué estamos acá?',
    bullets: [
      'La IA ya está en el flujo de desarrollo',
      'Muchos la usan como chatbot de código',
      'Falta método: spec, contexto, validación',
    ],
    teacherNotes: {
      time: '2 min',
      explain: 'El problema no es acceso a modelos. Es usarlos como oráculo y reescribir lo que sale.',
      mainIdea: 'La herramienta existe; falta el oficio alrededor.',
      example: 'Anécdota corta: un prompt que generó un Express en un proyecto Next. 20 segundos, no 3 minutos.',
      question: '¿Alguna vez reescribieron de cero lo que les generó la IA?',
      transition: 'Eso no es “la IA es mala”. Es un proceso sin spec ni contexto.',
      note: 'Si nadie levanta la mano en la pregunta 1, preguntar por Copilot. Casi siempre hay alguien.',
    },
  },
  {
    id: 3,
    section: 'Introducción',
    title: 'Cómo cambió el desarrollo',
    bullets: ['IDE → Git → Cloud → CI/CD → AI Coding → Agentes', 'Cada salto cambió el rol, no solo la herramienta'],
    diagram: 'IDE → Git → Cloud → CI/CD → AI → Agentes',
    teacherNotes: {
      time: '2 min',
      explain: 'Recorrer la línea sin historia de cada uno. El punto es el último salto.',
      mainIdea: 'Agentic Development no es una moda de autocompletado: es trabajo delegable y supervisado.',
      example: 'Notepad vs IDE vs Copilot vs un agente que corre tests. Cuatro oficios distintos.',
      question: '¿Cuál salto les cambió más la forma de trabajar hasta ahora?',
      transition: 'Ese último salto exige una pregunta nueva.',
    },
  },
  {
    id: 4,
    section: 'Introducción',
    title: 'La pregunta de estas 2 horas',
    bullets: [
      'De “pedile código a la IA”',
      'A diseñar y supervisar un proceso con agentes',
      'Especificar · Contextualizar · Validar',
    ],
    diagram: 'REQUERIMIENTO → SPEC → CONTEXTO → PLAN → AGENTE → TEST → REVIEW → SOFTWARE',
    teacherNotes: {
      time: '2 min',
      explain: 'Dejar el flujo en pantalla. Es el estribillo del workshop.',
      mainIdea: 'La habilidad nueva no es promptear con gracia. Es dirigir un proceso.',
      example: 'Señalar: hoy practicamos hasta PLAN en clase; IMPLEMENTAR es el desafío de la casa.',
      question: '¿En qué cajita de este flujo usan IA hoy, y en cuál nunca?',
      transition: 'Para dirigir agentes hay que saber qué son — y qué no.',
      note: 'Mini-actividad del bloque 1 si no la hicieron al hablar. Si ya mapeó el aula, seguir.',
    },
  },
  {
    id: 5,
    section: 'Ecosistema',
    title: 'Un modelo no es un agente',
    bullets: [
      'Proveedor entrena el modelo; el modelo infiere tokens',
      'Asistente: respuesta + un poco de contexto (archivo, IDE)',
      'Agente: objetivo + contexto + herramientas + iteración',
    ],
    diagram: 'MODELO + OBJETIVO + CONTEXTO + HERRAMIENTAS + ITERAR = AGENTE',
    teacherNotes: {
      time: '4 min',
      explain: 'Tres capas. Sin ranking de marcas. La fórmula se apunta y se reusa toda la clase.',
      mainIdea: 'Un modelo responde. Un agente actúa, observa y corrige.',
      example: 'Mismo problema (cupo 3): chatbot explica la regla; asistente completa el test; agente implementa según SPEC.md y corre Vitest.',
      question: 'La herramienta que nombraron al inicio: ¿chatbot, asistente o agente? ¿Por qué?',
      transition: 'Hagamos eso en voz alta con cinco nombres conocidos.',
      note: 'Acá corre la mini-actividad de clasificar (4 min). No la saltees: fija el vocabulario.',
    },
  },
  {
    id: 6,
    section: 'Ecosistema',
    title: 'Límites que importan en el trabajo',
    bullets: [
      'Context window: prompt + archivos + respuesta',
      'Alucinaciones: plausible ≠ verdadero',
      'Sin tools, no hay tests ni archivos: solo texto',
    ],
    teacherNotes: {
      time: '3 min',
      explain: 'Práctico, cero matemáticas. Tokens = hay un tanque de nafta. Alucinación = inventa imports.',
      mainIdea: 'Los límites se mitigan con contexto, tests y review, no con un modelo más grande “de fe”.',
      example: 'from "@/lib/appointments" que no existe. El test es el detector, no la confianza del chat.',
      question: '¿La IA les “olvidó” una instrucción de hace diez mensajes?',
      transition: 'Si el contexto es el tanque, hay que aprender a cargarlo. Eso se llama Context Engineering… después del entorno.',
      note: 'No explicar temperatura salvo pregunta. Si preguntan: “más creativo, menos predecible; en código suele molestar”.',
    },
  },
  {
    id: 7,
    section: 'Ecosistema',
    title: 'El mapa',
    bullets: [
      'Proveedor → Modelo → Agente → Entorno → Herramientas → Proyecto',
      'Cursor (ADE de referencia), Copilot, Claude Code: ejemplos, no la respuesta',
      'Conceptos > logos',
    ],
    diagram: 'PROVEEDOR → MODELO → AGENTE → CLIENTE → HERRAMIENTAS → PROYECTO',
    teacherNotes: {
      time: '2 min',
      explain: 'Una pasada visual. El alumno tiene que poder ubicar una herramienta nueva acá el mes que viene.',
      mainIdea: 'Las marcas rotan. El mapa no.',
      example: 'Si mañana sale “Forge IDE”, preguntar: ¿tiene agente con tools o solo chat?',
      question: '¿Qué capa les resulta más borrosa todavía?',
      transition: 'Cambiemos de capa: el entorno donde trabajan ustedes.',
    },
  },
  {
    id: 8,
    section: 'IDE → ADE',
    title: 'IDE',
    bullets: ['Desarrollador → editor → código', 'Un cursor, un hilo, una tarea', 'El oficio = escribir y depurar'],
    diagram: 'DESARROLLADOR → IDE → CÓDIGO',
    teacherNotes: {
      time: '1 min',
      explain: 'Baseline. No romanticen ni denigren. Es el suelo.',
      mainIdea: 'Todo gira alrededor del archivo abierto.',
      example: 'VS Code, IntelliJ, Neovim. Da igual.',
      question: '¿Cuánto de su día es editor vs terminal vs browser vs reunión?',
      transition: 'Métanle un modelo al costado.',
    },
  },
  {
    id: 9,
    section: 'IDE → ADE',
    title: 'AI IDE',
    bullets: [
      'Desarrollador ↔ editor ↔ asistente',
      'Tab, chat, editar selección',
      'Sigue conduciendo cada cambio',
    ],
    diagram: 'DESARROLLADOR ↔ IDE ↔ ASISTENTE',
    teacherNotes: {
      time: '2 min',
      explain: 'Es lo que la mayoría ya usa. Nombrar Copilot y Cursor Tab como asistentes, no como agentes, salvo Agent mode.',
      mainIdea: 'Asistir ≠ delegar un objetivo completo.',
      example: 'Aceptar 8 líneas de un test vs “andá y resolvé el ticket”.',
      question: '¿Qué porcentaje del autocompletado aceptan sin leer?',
      transition: 'El siguiente salto mueve el centro: de cursor a objetivo.',
      note: 'Si alguien usa Cursor Agent, decir: “eso ya pisa el ADE. Lo vemos ahora.”',
    },
  },
  {
    id: 10,
    section: 'IDE → ADE',
    title: 'ADE',
    bullets: [
      'Agentic Development Environment',
      'Desarrollador → orquestador → agentes (a menudo en paralelo)',
      'La unidad de trabajo es el objetivo y el diff, no el cursor',
    ],
    diagram: 'DEV → ORQUESTADOR → Backend / QA / Docs',
    teacherNotes: {
      time: '3 min',
      explain: 'Concepto, no producto. Tabla comparativa en contenidos si precisan detalle.',
      mainIdea: 'El entorno se diseña para ejecutar trabajo de agentes con revisión humana.',
      example: 'Un agente API, otro tests, vos rechazás el diff que tocó auth.',
      question: '¿Qué dos tareas de su proyecto no se pisan de archivos y podrían ir en paralelo?',
      transition: 'Cursor es el ADE de referencia de este dibujo. No el examen de atajos.',
      note: 'Mini-actividad de paralelizar acá si el grupo está despierto. 2 min.',
    },
  },
  {
    id: 11,
    section: 'IDE → ADE',
    title: 'Cursor, como ADE de referencia',
    bullets: [
      'Agent mode + tools + diffs revisables',
      'Rules y Skills dan forma al agente entre sesiones',
      'cursor.com — paradigma, no tutorial de atajos',
    ],
    teacherNotes: {
      time: '2 min',
      explain: '90–120 s. Cursor = ADE de referencia: Agent, Rules, Skills, MCP. Worktrees/sesiones aisladas si hablan de paralelo.',
      mainIdea: 'Un ADE no es chat al costado: es dirigir trabajo con evidencia y revisión.',
      example: 'Rule: no toques auth. Skill: primero el test del edge case. Agent implementa CA3 según SPEC.md.',
      question: '¿Usan Cursor Agent o solo Tab/chat?',
      transition: 'Aunque el entorno sea ADE, si SPEC/Rules faltan, el agente improvisa el producto.',
      note: 'Si van tarde: esta slide se dice de pie y se avanza. No abrir la docs de Cursor en vivo.',
    },
  },
  {
    id: 12,
    section: 'Contexto',
    title: 'El contexto decide el resultado',
    bullets: [
      'Resultado = Modelo + Prompt + Contexto + Herramientas',
      'Un prompt brillante sobre un repo vacío = tutorial genérico',
      'Context Engineering = curar qué evidencia ve el agente',
    ],
    teacherNotes: {
      time: '3 min',
      explain: 'Ecuación en pizarra. Prompt ≠ contexto. Este es el bloque que no se recorta.',
      mainIdea: 'El oficio diferencial es decidir qué información entra, no adjetivar el prompt.',
      example: 'Correr Demo 1 ahora: mismo pedido, con y sin stack/SPEC/“no toques auth”.',
      question: 'Antes de ver la demo: ¿qué va a inventar el prompt pobre?',
      transition: 'Miren la salida. Después hablamos de ventanas y capas.',
      note: 'Demo 1 es obligatoria. Si no hay red, leer las dos respuestas de la sección Demos.',
    },
  },
  {
    id: 13,
    section: 'Contexto',
    title: 'Capas — y un tanque que no es infinito',
    bullets: [
      'Prompt → conversación → proyecto → repo → arquitectura → organización',
      'La ventana de contexto incluye la respuesta',
      'Más archivos ≠ mejor: hay que curar',
    ],
    diagram: 'PROMPT → CONVERSACIÓN → PROYECTO → REPO → ARQUITECTURA → ORG',
    teacherNotes: {
      time: '4 min',
      explain: 'De adentro hacia afuera. Cada capa que falta, el modelo la inventa.',
      mainIdea: 'SPEC.md + Rules + Skills (y AGENTS.md) son contexto reutilizable, no burocracia.',
      example: 'SPEC del cupo 3 + Rule “no toques auth” + Skill “test antes que código”. Mini-actividad: qué 5 archivos para “cancelar turno”.',
      question: '¿Qué archivo de su repo nunca le mostraron a la IA y deberían?',
      transition: 'El agente también necesita manos, no solo evidencia.',
      note: 'Si el tiempo aprieta, saltar Organización. Repo + spec alcanzan.',
    },
  },
  {
    id: 14,
    section: 'MCP',
    title: 'De copiar y pegar a actuar',
    bullets: [
      'En Cursor: Agent ya lee el repo y corre tests',
      'MCP: enchufe cuando el trabajo vive fuera del repo',
      'GitHub, Postgres, Jira… — después de SPEC/Rules',
    ],
    diagram: 'AGENTE → MCP CLIENT → MCP SERVER → HERRAMIENTA → SISTEMA',
    teacherNotes: {
      time: '8 min del bloque, ~3 min esta slide si recortan',
      explain: 'Repo local: tools de Cursor. Sistemas externos: MCP. Cero implementación de servers.',
      mainIdea: 'MCP no hace más inteligente al modelo. Le da manos.',
      example: 'Issue #412 copiado al chat vs “tomá el issue y abrí el PR”.',
      question: '¿Qué sistema de su día siguen copiando a mano al chat?',
      transition: 'Manos (tools/MCP) + evidencia (SPEC/Rules) no alcanzan si el pedido es vago. Vamos al flujo completo.',
      note: 'Bloque recortable. Si van tarde: problema → diagrama → “está en Recursos” → siguiente.',
    },
  },
  {
    id: 15,
    section: 'Desarrollo',
    title: 'Del requerimiento al software',
    bullets: [
      'Ocho pasos. Un enunciado. Cero magia.',
      'Hoy: walkthrough de “reservar un turno”',
      'Después: ustedes, con gastos, hasta el plan',
    ],
    diagram: 'REQUERIMIENTO → SPEC → CONTEXTO → PLAN → IMPL → TEST → REVIEW',
    teacherNotes: {
      time: '1 min',
      explain: 'Mapa del resto de la clase presencial y del desafío.',
      mainIdea: 'La metodología es el producto del workshop. El dominio se puede cambiar.',
      example: 'Turnos = demo del docente. Gastos = práctica. Turnos otra vez = desafío con spec dura.',
      question: '¿“Permitir reservar un turno” les alcanza para implementar mañana?',
      transition: 'Spoiler: no. Por eso la próxima slide duele.',
    },
  },
  {
    id: 16,
    section: 'Desarrollo',
    title: 'El requerimiento pobre',
    bullets: [
      '“El sistema debe permitir que un usuario reserve un turno.”',
      'Ambiguo = el modelo diseña el producto en silencio',
      'Garbage in, software plausible, negocio incorrecto',
    ],
    teacherNotes: {
      time: '3 min',
      explain: 'Pedir 5 preguntas al aula antes de mostrar las vuestras. Escribirlas. Completar concurrencia si no sale.',
      mainIdea: 'Si no se decide en la spec, se decide en el código sin aprobación.',
      example: 'El agente asume 1 reserva, sin overlap, sin cancelación, userId en el body.',
      question: '¿Quién reserva? ¿Cuántas a la vez? ¿Dos POST al mismo horario? ¿Cancelar hasta cuándo?',
      transition: 'Esas respuestas, escritas como reglas, son la spec.',
      note: 'Mini-actividad de 5 preguntas acá. 3 min. Es el calentamiento de la actividad larga.',
    },
  },
  {
    id: 17,
    section: 'Desarrollo',
    title: 'SPEC, Rules y plan (antes del diff)',
    bullets: [
      'SPEC.md: reglas verificables + fuera de alcance',
      'Rules/Skills: cómo trabaja el agente; “qué no tocar”',
      '“Generá un plan. No modifiques código.”',
    ],
    teacherNotes: {
      time: '4 min',
      explain: 'Mostrar 4 reglas de ejemplo (cupo 3, slot único, 24 h, no pasado). Prompt del plan en pantalla.',
      mainIdea: 'Un plan malo se corrige en un párrafo. Un módulo malo, no.',
      example: 'Si hay tiempo, Demo 3. Si no, leer un plan y tachar lo que falta (tests, auth).',
      question: '¿Qué pondrían en la sección “No toques” de su proyecto?',
      transition: 'Plan aprobado: ahí sí código, tests y un revisor que no sea el autor.',
      note: 'No implementar turnos en vivo. Resistir al aula.',
    },
  },
  {
    id: 18,
    section: 'Desarrollo',
    title: 'Implementar, romper, revisar',
    bullets: [
      'Diffs acotados, tests existentes en verde',
      'Edge cases: cuarto cupo, doble slot, ventana 24 h',
      'Otro agente (o vos en otra sesión) hace QA — Human in the Loop al final',
    ],
    diagram: 'IMPLEMENTADOR → CÓDIGO → QA → REVIEW HUMANO',
    teacherNotes: {
      time: '3 min',
      explain: 'Tres hábitos: no aceptar el diff gigante, tests que intentan romper reglas, autor ≠ reviewer.',
      mainIdea: 'Los tests no tienen ego. Los agentes, a veces, sí.',
      example: 'El implementador “cubre” el happy path. El QA pide el cuarto turno.',
      question: '¿Quién revisa sus PRs hoy? ¿Se auto-aprueban con IA incluida?',
      transition: 'Practiquen hasta el plan. El código completo es el desafío.',
    },
  },
  {
    id: 19,
    section: 'Práctica',
    title: 'Actividad · 25 min · gastos',
    bullets: [
      'Enunciado: “registrar gastos con categoría y monto”',
      'Duplas: preguntas → reglas → spec → contexto → prompt → plan',
      'No hace falta programar',
    ],
    teacherNotes: {
      time: '25 min de reloj — no de slide',
      explain: 'Leer el enunciado. Mostrar el timing en la plataforma. Circular. Plan semilla al minuto 18.',
      mainIdea: 'Transferir el método a otro dominio. El entregable es el oficio, no la app.',
      example: 'Decisiones de ejemplo si una dupla se traba: un usuario, ARS, categorías cerradas, sin auth.',
      question: 'Al plenario: ¿qué supuesto iban a dejar colar?',
      transition: 'Lo que acaban de hacer, con una spec más dura, es el desafío.',
      note: 'Proteger este bloque. Ver notas en Actividad práctica. Debrief 3 min, máximo 2 duplas.',
    },
  },
  {
    id: 20,
    section: 'Cierre',
    title: 'El oficio que gana valor',
    bullets: [
      'Análisis, spec, contexto, arquitectura, tests de negocio, review',
      'Pierde valor relativo: boilerplate, memorizar APIs, copy-paste',
      'Human in the Loop no es opcional',
    ],
    teacherNotes: {
      time: '3 min',
      explain: 'Dos columnas. No decir que memorizar APIs “no sirve”: decir que ya no diferencia.',
      mainIdea: 'Invertir horas en lo que la IA no puede firmar: el criterio.',
      example: 'Junior que solo acepta tabs vs junior que escribe CA y rechaza un diff.',
      question: '¿Cuál de las que ganan valor van a practicar esta semana en el desafío?',
      transition: 'Riesgos, en una slide, para no romantizar.',
    },
  },
  {
    id: 21,
    section: 'Cierre',
    title: 'Riesgos y prácticas',
    bullets: [
      'Alucinaciones, prompt injection, dependencia sin tests',
      'Spec antes de delegar · contexto curado · plan ≠ impl ≠ review',
      'Validar con evidencia, no con confianza del modelo',
    ],
    teacherNotes: {
      time: '3 min',
      explain: 'Tres riesgos, cuatro prácticas. Nada de miedo existencial.',
      mainIdea: 'Velocidad sin validación es deuda. El desafío exige tests por eso.',
      example: 'SQL armado por concatenación “porque el agente lo vio en un blog”.',
      question: '¿Qué riesgo les pega más en su trabajo o cursada?',
      transition: 'Consigna de la casa. Reloj en 10 minutos para esto y el cierre.',
    },
  },
  {
    id: 22,
    section: 'Cierre',
    title: 'Desafío · reservas de turnos',
    bullets: [
      '4–6 h en 7 días · IA obligatoria y documentada',
      'Spec dada: cupo 3, slot único, 24 h, no pasado',
      'HTTP: ajena 403|404 · slot 409|400 (elegir y documentar)',
      'Entrega: PR con src, tests, README, SPEC.md, AI.md',
    ],
    teacherNotes: {
      time: '6 min',
      explain: 'Proyectar CA1–CA6. “El juez va a intentar el cuarto turno y el doble booking.” Mostrar plantillas.',
      mainIdea: 'Se evalúa dirigir el proceso, no programar a mano. SPEC dada manda sobre la del alumno.',
      example: 'AI.md débil = “usé ChatGPT”. AI.md sólida = rechazos, tests que fallaron, comando final.',
      question: '¿Qué herramienta van a usar para el plan? ¿Cuál para QA?',
      transition: 'Una frase y se cierra. Preguntas de entrega, no de teoría nueva.',
      note: 'Dejar URL del sitio y fecha. No abrir debate de stacks.',
    },
  },
  {
    id: 23,
    section: 'Cierre',
    title: 'La ventaja',
    bullets: [
      'No es escribir más rápido',
      'Es definir, contextualizar, dirigir y validar',
      'Gracias · el material queda en el sitio',
    ],
    teacherNotes: {
      time: '2 min',
      explain: 'Leer la quote. Aplauso corto. Fecha de entrega. Fin.',
      mainIdea: 'La IA puede escribir código. El oficio es dirigir, contextualizar y validar.',
      example: 'Quote del inicio, ahora con significado operativo.',
      question: '¿Qué se llevan que puedan usar mañana en un ticket real?',
      transition: 'Fin del workshop. Oficina de consultas: Recursos y Glosario.',
      note: 'No agregar un tema nuevo. Si sobran 5 min, una pregunta del desafío, no MCP avanzado.',
    },
  },
]

export const slideSections = [...new Set(slides.map((s) => s.section))]
